const products = [
  { id: 1, name: "Crystal Clear UV Resin", category: "Resin & Molds", price: 385, icon: "💧" },
  { id: 2, name: "Pastel Polymer Clay Set", category: "Polymer Clay", price: 420, icon: "🟣" },
  { id: 3, name: "Boho Gold Enamel Charms", category: "Tools", price: 260, icon: "✦" },
  { id: 4, name: "Artisan Ceramic Glaze Kit", category: "Pottery Glaze", price: 680, icon: "◉" },
  { id: 5, name: "Mini Detail Brush Trio", category: "Tools", price: 195, icon: "🖌" },
  { id: 6, name: "Pressed Flower Mold Set", category: "Resin & Molds", price: 345, icon: "✿" },
  { id: 7, name: "Earth Tones Clay Bundle", category: "Polymer Clay", price: 510, icon: "●" },
  { id: 8, name: "Speckled Stoneware Glaze", category: "Pottery Glaze", price: 460, icon: "◐" },
];
let cart = JSON.parse(localStorage.getItem("blahami-cart") || "[]");
const peso = value => `₱${value.toLocaleString("en-PH")}`;
const grid = document.querySelector("#productGrid");

function renderProducts(category = "All") {
  grid.innerHTML = products.filter(p => category === "All" || p.category === category).map(p => `
    <article class="product-card">
      <div class="product-image"><button class="heart" aria-label="Save ${p.name}">♡</button><span>${p.icon}</span></div>
      <div class="product-info"><p>${p.category}</p><h3>${p.name}</h3><div class="product-bottom"><span class="price">${peso(p.price)}</span><button class="add-button" data-add="${p.id}"><span class="material-symbols-outlined">add</span> Add</button></div></div>
    </article>`).join("");
  document.querySelectorAll("[data-add]").forEach(button => button.addEventListener("click", () => addToCart(Number(button.dataset.add))));
}
function addToCart(id) {
  const item = cart.find(entry => entry.id === id);
  item ? item.quantity++ : cart.push({ id, quantity: 1 });
  localStorage.setItem("blahami-cart", JSON.stringify(cart));
  renderCart(); showToast();
}
function renderCart() {
  const count = cart.reduce((sum, item) => sum + item.quantity, 0);
  document.querySelector("#cartCount").textContent = count;
  const items = document.querySelector("#cartItems");
  items.innerHTML = cart.length ? cart.map(item => { const p = products.find(product => product.id === item.id); return `
    <div class="cart-item"><div class="cart-item-image" style="background:#dce6d6">${p.icon}</div><div><h3>${p.name}</h3><p>${peso(p.price)}</p></div><div class="quantity"><button data-quantity="${p.id}" data-change="-1">−</button><span>${item.quantity}</span><button data-quantity="${p.id}" data-change="1">+</button></div></div>`; }).join("") : '<div class="empty-cart"><span class="material-symbols-outlined">shopping_bag</span><p>Your tray is waiting for a project.</p></div>';
  document.querySelector("#cartTotal").textContent = peso(cart.reduce((sum, item) => sum + products.find(p => p.id === item.id).price * item.quantity, 0));
  document.querySelectorAll("[data-quantity]").forEach(button => button.addEventListener("click", () => changeQuantity(Number(button.dataset.quantity), Number(button.dataset.change))));
}
function changeQuantity(id, change) { const item = cart.find(entry => entry.id === id); if (item) item.quantity += change; cart = cart.filter(entry => entry.quantity > 0); localStorage.setItem("blahami-cart", JSON.stringify(cart)); renderCart(); }
function toggleCart(open) { document.querySelector("#cartDrawer").classList.toggle("open", open); document.querySelector("#overlay").classList.toggle("visible", open); document.querySelector("#cartDrawer").setAttribute("aria-hidden", String(!open)); }
function showToast() { const toast = document.querySelector("#toast"); toast.classList.add("show"); setTimeout(() => toast.classList.remove("show"), 1800); }
document.querySelectorAll(".category").forEach(button => button.addEventListener("click", () => { document.querySelector(".category.active").classList.remove("active"); button.classList.add("active"); renderProducts(button.dataset.category); }));
document.querySelector("#cartButton").addEventListener("click", () => toggleCart(true));
document.querySelector("#closeCart").addEventListener("click", () => toggleCart(false));
document.querySelector("#overlay").addEventListener("click", () => toggleCart(false));
document.querySelector("#menuButton").addEventListener("click", () => document.querySelector(".desktop-nav").classList.toggle("mobile-open"));
document.addEventListener("keydown", event => { if (event.key === "Escape") toggleCart(false); });
document.querySelector("#checkoutButton").addEventListener("click", () => { if (cart.length) { toggleCart(false); location.hash = "checkout"; } });
const views = ["shopView", "checkoutView", "authView", "profileView", "adminLoginView", "adminView", "fulfillmentView"];
const logo = "e0f4301b_56d2_4bb4_af0b_9e6e373d805e.jpg/screen.png";
const adminProducts = products.map((product, index) => ({ ...product, stock: [42, 18, 7, 3, 24, 12, 0, 9][index], active: index !== 6 }));
function setView(id) { views.forEach(view => document.querySelector(`#${view}`).style.display = view === id ? "block" : "none"); document.querySelector("#shopView").style.display = id === "shopView" ? "block" : "none"; document.querySelector(".desktop-nav")?.classList.remove("mobile-open"); window.scrollTo(0, 0); }
function sharedHeader(title, subtitle) { const adminActions = title === "Blahatí Studio" ? '<button class="text-link" id="adminLogout">Log out</button>' : '<a class="text-link" href="#shop">Back to shop</a>'; return `<div class="screen-header"><a class="brand" href="#shop"><img class="brand-mark" src="${logo}" alt="Blahatí gold monogram"><span><strong>${title}</strong><small>${subtitle}</small></span></a><div class="header-links">${adminActions}</div></div>`; }
function renderCheckout() {
  const subtotal = cart.reduce((sum, item) => sum + products.find(p => p.id === item.id).price * item.quantity, 0);
  document.querySelector("#checkoutView").innerHTML = `<div class="screen-shell">${sharedHeader("Cart & Checkout", "Blahatí CrArtsland official checkout")}<div class="screen-grid"><section><p class="eyebrow">Almost yours</p><h1 class="screen-title">Review your craft tray</h1><div class="panel">${cart.length ? cart.map(item => { const p = products.find(x => x.id === item.id); return `<div class="checkout-item"><span class="checkout-icon">${p.icon}</span><div><h3>${p.name}</h3><small>${item.quantity} × ${peso(p.price)}</small></div><strong>${peso(p.price * item.quantity)}</strong></div>`; }).join("") : '<p class="muted">Your cart is empty. Add a few supplies from the shop first.</p>'}</div><div class="panel form-panel"><h2>Shipping destination</h2><div class="form-grid"><label>Recipient name<input value="Juan Dela Cruz"></label><label>Mobile number<input value="+63 917 842 1928"></label><label>Barangay / street<input placeholder="House number and barangay"></label><label>City<input placeholder="City / municipality"></label><label>Province<input placeholder="Province"></label><label>ZIP code<input placeholder="0000"></label></div></div></section><aside class="summary-card"><p class="eyebrow">Order summary</p><h2>Ready to make</h2><div class="summary-line"><span>Subtotal</span><strong>${peso(subtotal)}</strong></div><div class="summary-line"><span>J&T Express</span><strong>₱85</strong></div><div class="summary-line total"><span>Total</span><strong>${peso(subtotal + (cart.length ? 85 : 0))}</strong></div><h3>Payment method</h3><label class="choice"><input type="radio" name="payment" checked> GCash <small>Mobile wallet redirect</small></label><label class="choice"><input type="radio" name="payment"> J&T Cash on Delivery <small>Pay upon arrival</small></label><label class="choice"><input type="radio" name="payment"> Credit / Debit Card <small>Visa or Mastercard</small></label><button class="button button-dark full-width" id="placeOrder">Place order <span class="material-symbols-outlined">arrow_forward</span></button></aside></div></div>`;
  document.querySelector("#placeOrder")?.addEventListener("click", () => { if (!cart.length) return showToast(); cart = []; localStorage.setItem("blahami-cart", "[]"); renderCart(); alert("Order placed! Your J&T Express tracking details will be sent by SMS."); location.hash = "profile"; });
}
function renderAuth() { document.querySelector("#authView").innerHTML = `<div class="auth-shell"><div class="auth-art"><img src="${logo}" alt="Blahatí gold monogram"><p class="eyebrow">Studio access</p><h1>Make space for<br><em>good ideas.</em></h1><p>Join the artisan community and track every craft supply order.</p></div><div class="auth-form">${sharedHeader("Welcome back", "Blahatí CrArtsland account")}<div class="auth-tabs"><button class="selected" data-auth="signin">Sign in</button><button data-auth="register">Create account</button></div><form id="authForm"><label>Mobile number or email<input required placeholder="917 123 4567 or you@email.com"></label><label>Password<input required type="password" placeholder="Enter your studio password"></label><button class="button button-dark full-width">Continue <span class="material-symbols-outlined">arrow_forward</span></button></form><p class="or">or continue with</p><div class="social-row"><button>Google</button><button>Facebook</button></div></div></div>`; document.querySelectorAll("[data-auth]").forEach(btn => btn.addEventListener("click", () => { document.querySelector(".auth-tabs .selected").classList.remove("selected"); btn.classList.add("selected"); document.querySelector("#authForm").querySelector("button").firstChild.textContent = btn.dataset.auth === "register" ? "Create account " : "Continue "; })); document.querySelector("#authForm").addEventListener("submit", event => { event.preventDefault(); alert("Welcome to your studio account."); location.hash = "profile"; }); }
function renderAdminLogin() { document.querySelector("#adminLoginView").innerHTML = `<div class="auth-shell admin-auth"><div class="auth-art"><img src="${logo}" alt="Blahatí gold monogram"><p class="eyebrow">Restricted workspace</p><h1>Welcome to<br><em>Blahatí Studio.</em></h1><p>Product, inventory, order, and J&T fulfillment controls for authorized staff only.</p></div><div class="auth-form">${sharedHeader("Studio admin login", "Separate staff access")}<div class="secure-note"><span class="material-symbols-outlined">shield</span><span>Staff workspace · Protected access</span></div><form id="adminLoginForm"><label>Admin email<input required type="email" placeholder="studio@blahati.ph"></label><label>Admin password<input required type="password" placeholder="Enter your admin password"></label><button class="button button-dark full-width">Enter studio <span class="material-symbols-outlined">arrow_forward</span></button></form><p class="admin-hint">Demo access: use any valid email and a password with 6+ characters.</p><a class="text-link" href="#auth">Customer sign in instead</a></div></div>`; document.querySelector("#adminLoginForm").addEventListener("submit", event => { event.preventDefault(); const password = event.target.querySelector('input[type="password"]').value; if (password.length < 6) { alert("Admin password must be at least 6 characters."); return; } sessionStorage.setItem("blahati-admin-auth", "true"); location.hash = "admin"; }); }
function renderProfile() { document.querySelector("#profileView").innerHTML = `<div class="screen-shell">${sharedHeader("My profile", "Customer account & delivery addresses")}<div class="profile-card"><div class="avatar">JD</div><div><p class="eyebrow">VIP artisan tier</p><h1>Juan Dela Cruz</h1><p class="muted">juan.delacruz@gmail.com · +63 917 842 1928</p></div></div><div class="screen-grid"><section><div class="section-heading"><div><p class="eyebrow">Doorstep fulfillment</p><h2>Delivery addresses</h2></div><button class="filter-button" id="addAddress">+ Add address</button></div><div class="address-list"><article class="panel address-card selected"><span class="badge">Home · Default</span><h3>Juan Dela Cruz</h3><p>Unit 4B, 28 Sampaguita St., Brgy. Kapitolyo<br>Pasig City, Metro Manila 1603<br>+63 917 842 1928</p><button class="text-link">Edit address</button></article><article class="panel address-card"><span class="badge neutral">Studio</span><h3>Blahatí Studio</h3><p>Lot 8, Mabini Avenue, Brgy. Lahug<br>Cebu City, Cebu 6000</p><button class="text-link">Make default</button></article></div></section><aside class="summary-card"><p class="eyebrow">Your craft journey</p><div class="profile-stat"><strong>14</strong><span>Handmade orders</span></div><div class="profile-stat"><strong>3</strong><span>Custom drops</span></div><h3>Recent orders</h3><p class="order-row"><b>BLH-8942</b><span class="badge">In transit</span></p><p class="order-row"><b>BLH-8871</b><span class="badge neutral">Delivered</span></p></aside></div></div>`; document.querySelector("#addAddress").addEventListener("click", () => alert("Address form ready for your new Philippine delivery destination.")); }
function renderAdmin() { document.querySelector("#adminView").innerHTML = `<div class="screen-shell">${sharedHeader("Blahatí Studio", "Admin · Product catalog manager")}<div class="admin-nav"><a class="active" href="#admin">Products</a><a href="#fulfillment">Orders <b>14</b></a><a href="#admin">Categories</a><a href="#admin">Analytics</a></div><div class="kpi-grid"><div class="kpi"><small>Active products</small><strong>48</strong><span>+2 this week</span></div><div class="kpi warning"><small>Inventory alert</small><strong>3 <small>low</small> · 1 <small>out</small></strong><span>Needs attention</span></div><div class="kpi sales"><small>Today's studio sales</small><strong>₱14,850</strong><span>19 orders</span></div></div><div class="admin-toolbar"><input id="adminSearch" placeholder="Search SKU, craft product, tag..."><button class="button button-dark" id="addProduct">+ Add new craft item</button></div><div class="admin-products" id="adminProducts"></div></div>`; const draw = () => { const query = document.querySelector("#adminSearch").value.toLowerCase(); document.querySelector("#adminProducts").innerHTML = adminProducts.filter(p => p.name.toLowerCase().includes(query) || p.category.toLowerCase().includes(query)).map(p => `<article class="admin-product panel"><div class="admin-product-top"><span class="admin-icon">${p.icon}</span><div><h3>${p.name}</h3><small>SKU: ${p.category.slice(0, 3).toUpperCase()}-${p.id} · ${p.category}</small></div><label class="toggle"><input type="checkbox" ${p.active ? "checked" : ""}><span></span></label></div><div class="admin-edit"><label>Price (PHP)<input type="number" value="${p.price}"></label><div><small>Quick stock count</small><div class="stock-stepper"><button data-stock="${p.id}" data-change="-1">−</button><strong>${p.stock}</strong><button data-stock="${p.id}" data-change="1">+</button></div></div></div><div class="admin-actions"><button class="text-link">Edit details</button><button class="save-button">Save changes</button></div></article>`).join(""); document.querySelectorAll("[data-stock]").forEach(btn => btn.addEventListener("click", () => { const item = adminProducts.find(p => p.id === Number(btn.dataset.stock)); item.stock = Math.max(0, item.stock + Number(btn.dataset.change)); draw(); })); }; document.querySelector("#adminSearch").addEventListener("input", draw); document.querySelector("#addProduct").addEventListener("click", () => alert("New craft item drawer opened.")); draw(); }
function renderFulfillment() { document.querySelector("#fulfillmentView").innerHTML = `<div class="screen-shell">${sharedHeader("Blahatí Studio", "Orders & J&T fulfillment")}<div class="section-heading"><div><p class="eyebrow">Operations dashboard</p><h1 class="screen-title">Today's dispatch health</h1></div><span class="badge">Cutoff: 5:30 PM</span></div><div class="kpi-grid fulfillment-kpis"><div class="kpi warning"><strong>14</strong><small>To ship / pack</small><span>6 need packing · 8 ready</span></div><div class="kpi"><strong>28</strong><small>In transit (J&T)</small><span>Metro Manila & provinces</span></div><div class="kpi sales"><strong>₱14,850</strong><small>Delivered & remitted</small><span>19 orders</span></div><div class="kpi"><strong>1 order</strong><small>Returns / cancelled</small><span>Customer rescheduled</span></div></div><section class="pickup panel"><div><span class="jt-badge">J&T Express</span><p class="eyebrow">Scheduled courier pickup</p><h2>Today, 4:00 PM – 6:00 PM</h2><p class="muted">14 parcels ready for dispatch seal · Rider: Kuya Arnel</p></div><button class="button button-dark" id="manifestButton">Generate manifest</button></section><div class="section-heading"><h2>Fulfillment queue</h2><button class="filter-button" id="printWaybills">Print waybills</button></div><div class="panel fulfillment-row"><div><span class="badge warning-badge">Ready for handover</span><h3>BLH-8942 · Juan Dela Cruz</h3><p class="muted">GCash ref: GCS-992184 · 2 items</p></div><strong>JT90412849PH</strong><button class="save-button" data-fulfill>Mark handed over</button></div><div class="panel fulfillment-row"><div><span class="badge neutral">In transit</span><h3>BLH-8938 · Carlo Reyes</h3><p class="muted">J&T Express · 1 item</p></div><strong>JT90412821PH</strong><button class="filter-button">Track parcel</button></div></div>`; document.querySelector("#manifestButton").addEventListener("click", () => alert("Manifest generated for 14 J&T parcels.")); document.querySelector("#printWaybills").addEventListener("click", () => alert("Waybill batch prepared for printing.")); document.querySelector("[data-fulfill]").addEventListener("click", event => { event.target.textContent = "Handed over"; event.target.disabled = true; showToast(); }); }
function route() { const requested = location.hash.slice(1) || "shop"; const protectedRoute = requested === "admin" || requested === "fulfillment"; if (protectedRoute && sessionStorage.getItem("blahati-admin-auth") !== "true") { if (requested !== "admin-login") location.hash = "admin-login"; renderAdminLogin(); setView("adminLoginView"); return; } const routeName = requested; const map = { shop: "shopView", checkout: "checkoutView", auth: "authView", profile: "profileView", "admin-login": "adminLoginView", admin: "adminView", fulfillment: "fulfillmentView" }; if (routeName === "checkout") renderCheckout(); if (routeName === "auth") renderAuth(); if (routeName === "profile") renderProfile(); if (routeName === "admin-login") renderAdminLogin(); if (routeName === "admin") renderAdmin(); if (routeName === "fulfillment") renderFulfillment(); setView(map[routeName] || "shopView"); const logout = document.querySelector("#adminLogout"); if (logout) logout.addEventListener("click", () => { sessionStorage.removeItem("blahati-admin-auth"); location.hash = "admin-login"; }); }
document.querySelectorAll("[data-route]").forEach(link => link.addEventListener("click", route));
window.addEventListener("hashchange", route);
renderProducts(); renderCart();
route();
